### ISSUE TITLE
Typo in output filename

### ISSUE THREAD

**Issue by michaelsauter** [lucachr/nitrogen#7]
See https://github.com/lucachr/nitrogen/blob/master/nitrogen#L75. 

In general, I was a bit confused to get this file at all, I don't think it's mentioned in the readme?

**Comment by lucachr** [comment]
Thank you for noticing! Actually, I'm a bit surprised to see that line in the script. I think that I've forgotten it here from some debugging session. I'll fix it as soon as I can.

**Comment by michaelsauter** [comment]
@lucachr Thanks for the quick fixes! I am using nitrogen now for [github.com/michaelsauter/crane](https://github.com/michaelsauter/crane). Not shipping nitrogen with the repo right now, but at least `nitrogen --freeze` allowed me to quickly pin the versions for me. Thanks for the tool. I really like it so far :)

**Comment by lucachr** [comment]
You're most welcome! I'm glad that you've found nitrogen useful and that you like it. If you spot other bugs or if you have other suggestions, don't hesitate to open a new issue. :)
